AMQQUTIL ; IHS/CMI/THL - RETURNS IF USER HOLDER OF PARTICULAR SECURITY KEY ;
 ;;2.0;IHS PCC SUITE;;MAY 14, 2009
 ;-----
KEYCHECK(AMQQKEY)  ; - EP - CHECK FOR KEY HOLDING
 Q $S(('$D(DUZ)#2):0,1:$D(^XUSEC(AMQQKEY,DUZ)))
 ;
DFNINC    ; - EP - Gets the next valid DFN when random sampling
 Q:$D(^DPT(AMQP(0)))
 F  S AMQP(0)=AMQP(0)+$R(AMQP("$R")) Q:$D(^DPT(AMQP(0)))  S:'$O(^DPT(AMQP(0))) AMQP(0)=0 Q:'AMQP(0)
 Q
