BGPGUA ; IHS/CMI/LAB - BGP Gui Utilities 03/11/2010 3:28:39 PM ;
 ;;11.1;IHS CLINICAL REPORTING SYSTEM;;JUN 27, 2011;Build 33
 ;
 ;
 ;
DEBUG(RETVAL,BGPSTR) ;run the debugger
 D DEBUG^%Serenji("SEARCH^BGPGUA(.RETVAL,.BGPSTR)")
 Q
 ;
ADO ;EP -- setup the ADO string for each call
 S BGPX="MERR^BGPGU",@^%ZOSF("TRAP") ; m error trap
 K ^BGPTMP($J)
 S RETVAL="^BGPTMP("_$J_")"
 Q
 ;
SEARCH(RETVAL,BGPSTR) ;-- return search results to Search
 N BGPDA,BGPI,P,BGPFL,BGPIDX,BGPGB,BGPS,BGPSZ,BGPL,BGPTGT,BGPFLDS,BGPSCR,BGPPR,BGPFLD1,BGPFLD2,BGPDT
 S P="|"
 S BGPI=0
 S X="MERR^BGPGU",@^%ZOSF("TRAP") ; m error trap
 S RETVAL="^BGPTMP("_$J_")"
 K ^BGPTMP($J)
 K ^BGPTMPD($J)
 S BGPTGT="^BGPTMPD("_$J_")"  ;target for find^dic lookup
 S BGPFL=$P(BGPSTR,P)
 I $E(BGPFL,1,1)=0 S BGPFL=+BGPFL
 S BGPIDX=$P(BGPSTR,P,2)
 I BGPIDX]"" S BGPIDX=$TR(BGPIDX,"*","^")
 S BGPS=$P(BGPSTR,P,3)
 I BGPFL=9002012.2,BGPS="" S BGPIDX="BA"
 S BGPFLD1=$P(BGPSTR,P,4)
 S BGPFLD2=$P(BGPSTR,P,5)
 S BGPSCR=$P(BGPSTR,P,6)
 S BGPDT=$P(BGPSTR,P,8)
 I $G(BGPSCR)["" S BGPSCR=$TR(BGPSCR,"*","^")
 S BGPPR=$P(BGPSTR,P,7)
 S BGPDT=$P(BGPSTR,P,8)
 I BGPFLD1["." S BGPFLD1=+BGPFLD1
 I BGPFLD2["." S BGPFLD2=+BGPFLD2
 I BGPFLD2=0 S BGPFLD2=""
 S BGPFLDS=$S(BGPFLD2]"":BGPFLD1_";"_BGPFLD2,1:BGPFLD1)
 I BGPS="" D
 . D LIST^DIC(BGPFL,"",BGPFLDS,"","","",BGPS,BGPIDX,BGPSCR,"",BGPTGT,"BGPERRR(1)")
 I BGPS]"" D
 . D FIND^DIC(BGPFL,"",BGPFLDS,"",BGPS,"",BGPIDX,BGPSCR,"",BGPTGT,"BGPERRR(1)")
 S @RETVAL@(0)="T00010BMXIEN^T00050Value1^T00080Value2"_$C(30)
 S BGPDA=0  F  S BGPDA=$O(@BGPTGT@("DILIST","ID",BGPDA)) Q:'BGPDA  D
 . N BGPIEN,BGPBMX
 . S BGPIEN=0 F  S BGPIEN=$O(@BGPTGT@("DILIST","ID",BGPDA,BGPIEN)) Q:'BGPIEN  D
 .. S BGPBMX=$G(@BGPTGT@("DILIST",2,BGPDA))
 .. S BGPFLD(BGPIEN)=$G(@BGPTGT@("DILIST","ID",BGPDA,BGPIEN))
 . Q:'$G(BGPBMX)
 . S BGPI=BGPI+1
 . S @RETVAL@(BGPI)=BGPBMX_U_BGPFLD(BGPFLD1)_U_$S($G(BGPFLD2):$G(BGPFLD(BGPFLD2)),1:"")_$C(30)
 S @RETVAL@(BGPI+1)=$C(31)
 Q
 ;
